export const subCategories = [
  { catValue: "panjabi", catName: "পাঞ্জাবী" },
  { catValue: "paijama", catName: "পায়জামা" },
  { catValue: "jobba", catName: "জুব্বা" },
  { catValue: "lungi", catName: "লুঙ্গী" },
  { catValue: "gamcha", catName: "গামছা" },
  { catValue: "muja", catName: "মুজা" },
  { catValue: "ator", catName: "আঁতর" },
  { catValue: "pagri", catName: "পাগড়ী" },
  { catValue: "koranMazid", catName: "কোরআন মাজীদ" },
  { catValue: "fajayeleAmol", catName: "ফাজায়েলে আমল" },
  { catValue: "muntakhabHadis", catName: "মুন্তাখাব হাদিস" },
  { catValue: "ahkameJindegi", catName: "আহকামে জিনদেগী" },
  { catValue: "ahkameNisa", catName: "আহকামে নিশা" },
  { catValue: "khejur", catName: "খেজুর" },
  { catValue: "modhu", catName: "মধু" },
  { catValue: "mixedBadam", catName: "মিক্সড বাদাম" },
  { catValue: "kaloJira", catName: "কালোজিরা" },
  { catValue: "sorisarToil", catName: "সরিষার তেল" },
  { catValue: "chinaJainamz", catName: "চায়না জায়নামাজ" },
  { catValue: "turkyJainamz", catName: "তুর্কি জায়নামাজ" },
  { catValue: "bedding", catName: "বেডিং" },
  { catValue: "moshari", catName: "মশারী" },
  { catValue: "tupi", catName: "টুপি" },
  { catValue: "meshwak", catName: "মেছওয়াক" },
  { catValue: "hijab", catName: "হিজাব" },
];

export default subCategories;